spring:
  profiles:
    active: local
  config:
    import: ./env-local.yml
  r2dbc:
    url: ${DB-URL}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  data:
    redis:
      host: ${REDIS-HOST}
      port: ${REDIS-PORT}
logging:
  level:
    root: info